// Generated by CoffeeScript 1.9.3

/*
Example: retrieving all links of yahoo.com
  $ npm up
  $ node_modules/.bin/coffee example.coffee
 */

(function() {
  require("./node-jquery");

  $.ajax({
    url: 'https://www.yahoo.com/',
    success: function(res) {
      var e, i, len, ref, results;
      ref = $(res).find("a");
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        e = ref[i];
        e = $(e);
        results.push(console.log("[" + (e.text()) + "](" + (e.attr("href")) + ")"));
      }
      return results;
    }
  });

}).call(this);
