// Generated by CoffeeScript 1.9.3
(function() {
  var $, XMLHttpRequest, window;

  (function() {}, window = require("jsdom").jsdom().defaultView, $ = require("jquery")(window), XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest, $.support.cors = true, $.ajaxSettings.xhr = function() {
    return new XMLHttpRequest;
  }, global.window = window, global.jQuery = $, global.$ = $)();

}).call(this);
